/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSectionRouteImport } from './routes/app.$section'
import { Route as OrganizationAcceptInvitationRouteImport } from './routes/organization.accept-invitation'
import { Route as AppTopicSlugRouteImport } from './routes/app.topic.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionRoute = AppSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppRoute,
} as any)
const OrganizationAcceptInvitationRoute =
  OrganizationAcceptInvitationRouteImport.update({
    id: '/organization/accept-invitation',
    path: '/organization/accept-invitation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTopicSlugRoute = AppTopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$section': typeof AppSectionRoute
  '/organization/accept-invitation': typeof OrganizationAcceptInvitationRoute
  '/app/': typeof AppIndexRoute
  '/app/topic/$slug': typeof AppTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/$section': typeof AppSectionRoute
  '/organization/accept-invitation': typeof OrganizationAcceptInvitationRoute
  '/app': typeof AppIndexRoute
  '/app/topic/$slug': typeof AppTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/$section': typeof AppSectionRoute
  '/organization/accept-invitation': typeof OrganizationAcceptInvitationRoute
  '/app/': typeof AppIndexRoute
  '/app/topic/$slug': typeof AppTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/$section'
    | '/organization/accept-invitation'
    | '/app/'
    | '/app/topic/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/$section'
    | '/organization/accept-invitation'
    | '/app'
    | '/app/topic/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/$section'
    | '/organization/accept-invitation'
    | '/app/'
    | '/app/topic/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrganizationAcceptInvitationRoute: typeof OrganizationAcceptInvitationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$section': {
      id: '/app/$section'
      path: '/$section'
      fullPath: '/app/$section'
      preLoaderRoute: typeof AppSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/organization/accept-invitation': {
      id: '/organization/accept-invitation'
      path: '/organization/accept-invitation'
      fullPath: '/organization/accept-invitation'
      preLoaderRoute: typeof OrganizationAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/topic/$slug': {
      id: '/app/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/app/topic/$slug'
      preLoaderRoute: typeof AppTopicSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSectionRoute: typeof AppSectionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTopicSlugRoute: typeof AppTopicSlugRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSectionRoute: AppSectionRoute,
  AppIndexRoute: AppIndexRoute,
  AppTopicSlugRoute: AppTopicSlugRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OrganizationAcceptInvitationRoute: OrganizationAcceptInvitationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
